nix := require("nix")
gdb := require("gdb")
make := require("make")
qmp-shell := require("qmp-shell")
ssh := require("ssh")
drgn := require("drgn")

nproc := shell("nproc")

tree := env("KBUILD_INPUT")
kdir := env("KBUILD_OUTPUT")

# See linux/scripts/subarch.include
arch := env("ARCH", shell("uname -m | sed -e s/i.86/x86/ -e s/x86_64/x86/ \
                 -e s/sun4u/sparc64/ \
                 -e /^arm64$$/!s/arm.*/arm/ -e s/sa110/arm/ \
                 -e s/s390x/s390/ \
                 -e s/ppc.*/powerpc/ -e s/mips.*/mips/ \
                 -e s/sh[234].*/sh/ -e s/aarch64.*/arm64/ \
                 -e s/riscv.*/riscv/ -e s/loongarch.*/loongarch/"))

image := if arch == "x86" { "bzImage" } else { "Image" }
serial := if arch == "x86" { "ttyS" } else { "ttyAMA" }

qmp_port  := "5550"
qgdb_port := "5551"
kgdb_port := "5552"
ssh_port  := "5553"
ssh_user  := "root"

export SHARED_DIR := env("SHARED_DIR", justfile_directory() + "/" + "shared")
export QEMU_KERNEL_PARAMS := "nokaslr console="+serial+"0 kgdboc="+serial+"1 loglevel=7"
export QEMU_OPTS := "-gdb tcp::"+qgdb_port+" \
                     -qmp tcp:localhost:"+qmp_port+",server,wait=off \
                     -serial mon:stdio \
                     -serial telnet::"+kgdb_port+",server,nowait \
                     -device vmcoreinfo"
export QEMU_NET_OPTS := "hostfwd=tcp::"+ssh_port+"-:22"

set positional-arguments

# List all possible commands
help:
    just -l --unsorted

# Install a development-ready config suitable for booting in the VM
[group("Building")]
install-vmconfig: && (make "olddefconfig")
    mkdir -p "{{kdir}}"
    cp "configs/{{arch}}/vmconfig" "{{kdir}}/.config"

# Run make in the kernel tree
[group("Building")]
make *args:
    {{make}} "-j{{nproc}}" -C "{{tree}}" "$@"

# Generate compile commands in the kernel tree
[group("Building")]
gen-compile-commands:
    {{tree}}/scripts/clang-tools/gen_compile_commands.py -d "{{kdir}}" -o "{{tree}}/compile_commands.json"

# Start QEMU with the custom-built kernel
[group("Virtualization")]
qemu:
    {{nix}} run path:./nix -- --kernel "{{kdir}}/arch/{{arch}}/boot/{{image}}"

# Start QEMU with the stock NixOS kernel
[group("Virtualization")]
qemu-stock:
    {{nix}} run path:./nix

# SSH into the VM
[group("Virtualization")]
ssh *args:
    {{ssh}} -o "StrictHostKeyChecking no" -o "UserKnownHostsFile /dev/null" "-p{{ssh_port}}" "{{ssh_user}}@localhost" "$@"

# Load compiled module in the VM
[no-cd]
[group("Virtualization")]
ssh-insmod name:
    gzip -c "{{name}}" | just ssh 'f=$(mktemp); gzip -d > $f; rmmod {{name}}; insmod $f; rm -fv $f'

# Send a QMP command to QEMU
[group("Virtualization")]
qmp-shell *args:
    {{qmp-shell}} -v "$@" "localhost:{{qmp_port}}"

# Dump guest memory to a file (e.g., to analyze with drgn)
[group("Virtualization")]
[no-cd]
qmp-dump file:
    echo "dump-guest-memory paging=false protocol=file:$(realpath "{{file}}")" | just qmp-shell
    chmod u+rw "{{file}}"

# Connect GDB to QEMU's GDB stub
[group("Debugging")]
qgdb *args:
    {{gdb}} "{{kdir}}/vmlinux" -ex 'target remote :{{qgdb_port}}' "$@"

# Trigger a KGDB breakpoint in the VM
[group("Debugging")]
[confirm]
@kgdb-break:
    echo 'send-key keys=[{"type":"qcode","data":"alt"},\
                         {"type":"qcode","data":"sysrq"},\
                         {"type":"qcode","data":"g"}]' | just qmp-shell

# Connect GDB to KGDB
[group("Debugging")]
kgdb *args:
    @just kgdb-break || true
    {{gdb}} "{{kdir}}/vmlinux" -ex 'target remote :{{kgdb_port}}' "$@"

# Start drgn with debugging symbols of the built kernel
[group("Debugging")]
[no-cd]
drgn *args:
    {{drgn}} -s "{{kdir}}/vmlinux" "$@"
